apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: gke-serviceaccounts
initializers:
  - name: serviceaccounts.cloud.google.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - pods
